server.port=1619
server.servlet.contextPath=/cache


isRIDFileEncrypted=true

request.dataBundle.encrypt.secretKey=hTMPSbPZPgYnRIyuB/Fs/ZGcnpySIffQ/Y43fCDUEe2Uw98DZd143GeOGF/fU1mm
request.dataBundle.encrypt.ivParameter=WDN+kwI6jKVTkFWQGuKyDGFRMT/Q+cD25k/qjGpyuE8=
response.dataBundle.encrypt.secretKey=1/XyoRmmqxtPR32FqTox8V7XhM9rzlj3J0Oyg/BYw+zoY6aqmDa0L5wOyOs96j85
response.dataBundle.encrypt.ivParameter=5D/bsY11IGv+2XQlkqNDTQIYfsd8o3obP4mCwzxcBz4=
management.endpoints.web.exposure.include=health
microservice.number=0
startupWithEmptyTenant=false

minimum.memory=64
maximum.memory=1024

logging.config=http://localhost:2689/cache/default/master/logback_cacheserver-spring.xml