server.port=2459
server.servlet.contextPath=/clipApi

request.dataBundle.encrypt.secretKey=58C7RcyBpNpdMIec4jP7XsnxvXLBC/4gwq/nEcjfWq4MqvtaqIvnSMrjMFlbkStIE+l448ZK/e6DGOi9
response.dataBundle.encrypt.secretKey=7XiF8zUgHX4IO3YcrJMIPMnfZBuOzZ5akZAIfI57RMLF/KKfskEaq4Zj2PP/fqdIGYHgiFHY9nn9tHtd

management.endpoints.web.exposure.include=health
microservice.number=0
cleaningImplementorClassName=posidex.prime360.engine.cleaning.NullContextCleaningImplementor
minimum.memory=64
maximum.memory=1024

buildNumber=1
buildDate=2025-06-04
logging.config=http://localhost:2689/clipApi/default/master/logback_clipApi-spring.xml   

isRIDFileEncrypted=true
   