commonPathForAllServices=E:/RA_PRIME360NOVA_Installation15102025
numberOfPartitions=3
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
initial.passcode=jdilh89r7812hnm34hf8qoshv4i3jv==
maxNumberOfClusters=4
# Port used when deploying the application as a WAR file on an external Tomcat server
agent.port=8443
# Uncomment the below line to use this port when running the application as a JAR
#agent.port=2466
#columns to be ignored while displaying in UI for base upload, bulk query and bulk addtotarget
#columnsToBeIgnored.uploads=SPOUSENAME
#AgentPerServer
#SingleAgentForAllServers
agentSSHApproach=AgentPerServer

batchIdForUIFunctionalFlow=Prime360UI
configServerUrl=http://localhost:2458
eurekaServerUrl=http://localhost:3161/eureka/
productVersionNumber=3.0

urlProtocol=http

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=100MB
server.tomcat.max-swallow-size=-1
server.tomcat.connection-timeout=1000000

#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=prime360
#server.ssl.key-store-type=PKCS12
#eureka.instance.hostname=localhost
#eureka.instance.secure-port-enabled=true
#eureka.instance.non-secure-port-enabled=false

gateway.url=http://localhost:1669
bypassGateway=false

agent.contextPath=/agent
dc.contextPath=/dc
dm.contextPath=/dm
icc.contextPath=/icc
primeapi.contextPath=/engine
primehof.contextPath=/hof
profileservice.contextPath=/profileservice
rb.contextPath=/rb
ra.contextPath=/ra
uam.contextPath=/uam

