##should not place spring.** properties here (won't be applied even if placed)
initiallimit=5
inactivityTimeOut=1800
maxActiveSession=100
maxIdleConnections=20
maxTotalConnections=200
clientdatabase.driverClassName=org.postgresql.Driver
clientdatabase.url=jdbc:postgresql://192.168.3.251:5432/prime360c1?stringtype=unspecified
clientdatabase.username=prime360user
clientdatabase.password=psx123

clientdatabase.minTotalConnections=200
clientdatabase.maxTotalConnections=200
clientdatabase.maxIdleConnections=20
clientdatabase.enableAutocommit=true
##initialProcess.passcode=wnSJNg2MKvvO0MCZfKVTbGsecG72FUJeRUHoFaR0vBEb0jFTJZUHVijQXq1mVXe77UpkSknV
productdatabase.driverClassName=org.postgresql.Driver
productdatabase.url=jdbc:postgresql://192.168.3.251:5432/prime360c1?stringtype=unspecified
productdatabase.username=prime360user
productdatabase.password=psx123
productdatabase.minTotalConnections=200
productdatabase.maxTotalConnections=200
productdatabase.maxIdleConnections=20
productdatabase.enableAutocommit=false
