# Port used when deploying the application as a WAR file on an external Tomcat server
server.port=2428
# Uncomment the below line to use this port when running the application as a JAR
# server.port=2458
server.servlet.contextPath=/dc
#FOR UTC OFFLINE SELECTION
offline.dateTimeConversionTypeFromSelection.0=2000
offline.dateTimeConversionTypeFromSelection.1=0
offline.dateTimeConversionTypeFromSelection.2=2000
offline.dateTimeConversionTypeFromSelection.3=-330
offline.dateTimeConversionTypeFromSelection.4=0
#offline.dateTimeConversionTypeFromSelection.5=0
offline.dateTimeConversionTypeFromSelection.6=2000

#FOR UTC OFFLINE INSERTION
offline.dateTimeConversionTypeFromInsertion.0=2000
offline.dateTimeConversionTypeFromInsertion.1=0
offline.dateTimeConversionTypeFromInsertion.2=0
offline.dateTimeConversionTypeFromInsertion.3=2000
offline.dateTimeConversionTypeFromInsertion.4=0
#offline.dateTimeConversionTypeFromInsertion.5=0
offline.dateTimeConversionTypeFromInsertion.6=2000

#FOR IST OFFLINE SELECTION
#offline.dateTimeConversionTypeFromSelection.0=0
#offline.dateTimeConversionTypeFromSelection.1=0
#offline.dateTimeConversionTypeFromSelection.2=2000
#offline.dateTimeConversionTypeFromSelection.3=-330
#offline.dateTimeConversionTypeFromSelection.4=-330
#offline.dateTimeConversionTypeFromSelection.5=0
#offline.dateTimeConversionTypeFromSelection.6=2000

#FOR IST OFFLINE INSERTION
#offline.dateTimeConversionTypeFromInsertion.0=4000
#offline.dateTimeConversionTypeFromInsertion.1=-330
#offline.dateTimeConversionTypeFromInsertion.2=-330
#offline.dateTimeConversionTypeFromInsertion.3=4000
#offline.dateTimeConversionTypeFromInsertion.4=-330
#offline.dateTimeConversionTypeFromInsertion.5=0
#offline.dateTimeConversionTypeFromInsertion.6=4000
maxNumberOfClusters=4
microservice.number=0
request.dataBundle.encrypt.secretKey=PSFbAUxxSBA/najjktubdsDQmx/Cnsgj2e8iEt4W53WcXsuvcz50Q73rZliUZRysC3379ry0Fa+55oW1
response.dataBundle.encrypt.secretKey=gTGuI/gsWO23YnDFvE22nHorBCLy/SBRDuwYQp+8L8vt2VaxlftRCRHIrOr/atIMPBji6Tmp6k9LVwmY
management.endpoints.web.exposure.include=health

minimum.memory=64
maximum.memory=1024

buildNumber=1
buildDate=2025-06-04

logging.config= http://localhost:2458/dataConverter/default/master/logback_dc-spring.xml
predml.Purge.query.0=truncate table probing_ids_customer
