# Port used when deploying the application as a WAR file on an external Tomcat server
server.port=8443
# Uncomment the below line to use this port when running the application as a JAR
# server.port=2578
# It gets the line count to display
FileDefinitionLinesCount=20
CTX_TYPE=IND
server.servlet.contextPath=/dm
modelservice.number=0
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Log file configurations
logging.file.name=${commonPathForAllServices}/logs/dictionarymanagement.log
logging.file.max-size=10MB
logging.file.max-history=60
minimum.memory=64
maximum.memory=1024
buildNumber=1
buildDate=2025-06-04