ExtractionType.city=1
ExtractionType.pincode=1
fetchSize=200
#cleaningObjectFilaName=cleaningObj
#performSerialization=false
#cleaningObjectFileName=D:/cleaningobject/object
#performSerialization=false
#

extractSDTV=true
#extractFloorNumberEtc=false
MSTR_NAME_SEQ=32@1000#1#5@0#6#7#1#9@16#9@32#1#2@18#1#4@17#1#10@19#1#5@1#11@2#5@3#1#14#1#13@4#1#16@20#1#11@5#1#
MSTR_DOB_SEQ=32@2000#35#19#
MSTR_PAN_SEQ=32@55#37#19#35#39^3#
MSTR_PASSPORT_SEQ=32@56#37#19#35#
MSTR_EQUALITY_SEQ=32@3000#37#19#35#
MSTR_ADDRESS_SEQ=32@4000#5@45#1#18#30#59@43#39^43#3@21#5@8#35#19#
MSTR_CITY_SEQ=32@70#5@45#1#60#31#1#5@44#1#33@22#35#
MSTR_PINCODE_SEQ=56@42#5@74#35#19#
MSTR_STATE_SEQ=32@72#37#19#
MSTR_ADDRESS_TYPE_SEQ=32@75#1#35#
MSTR_PHONENUMBER_SEQ=32@5000#61@7#35#
MSTR_PHONE_TYPE_SEQ=1#
MSTR_EMAILID_SEQ=32@6000#5@39#35#19#
MSTR_EMAIL_TYPE_SEQ=32@91#1#35#


houseNoExtraction.regexp=([a-zA-z-]*)(\\s{1}[a-zA-Z\\-\\ ]{0,3})?([0-9]+(([0-9]*|[a-zA-Z0-9]{0,3})\\-([0-9]*|[a-zA-Z0-9]{0,3}))*)([a-zA-Z\\-\\ ]{0,3}\\s{1})?([a-zA-z-]*)
houseNoExtraction.postfixIndex=7
houseNoExtraction.postwordIndex=8
houseNoExtraction.houseNoQuery=PSX_ICCTX_HNO_CLEANING_TABLE
houseNoExtraction.prefixIndex=2
houseNoExtraction.idIndex=3
houseNoExtraction.prewordIndex=1
houseNoExtraction.houseNoCount=3
houseNoExtraction.cleaningtableposidex=PSX_ICCTX_CLEANING_TABLE_HNO
houseNoExtraction.appendPostFix=false
houseNoExtraction.ignorepin=true
houseNoExtraction.houseNoSelectQuery=select trim(upper(variation)) variation,' '||trim(upper(standard))||' ' from psx_icctx_cleaning_table_hno where lookup_code=3 and effective_status='Y' order by lookup_id
houseNoExtraction.houseNoSelectQuery.MYSQL=select rtrim(ltrim(upper(variation))) variation,concat(' ',rtrim(ltrim(upper(standard))),' ') from cleaning_table_hno where lookup_code=3 and effective_status='Y' order by lookup_id
houseNoExtraction.houseNoSelectQuery.SQLSERVER=select rtrim(ltrim(upper(variation))) variation,' '+rtrim(ltrim(upper(standard)))+' ' from cleaning_table_hno where lookup_code=3 and effective_status='Y' order by lookup_id
houseNoExtraction.houseNoSelectQuery.DB2=select nvl(trim(upper(variation)),'') variation,' '||nvl(trim(upper(standard)),'')||' ' from cleaning_table_hno where lookup_code=3 and effective_status='Y' order by lookup_id
houseNoExtraction.houseNoSelectQuery.JAVADB=select trim(upper(variation)) variation,' '||trim(upper(standard))||' ' from cleaning_table_hno where lookup_code=3 and effective_status='Y' order by lookup_id

houseNoExtraction.ignorepin.anywhere=true
houseNoExtraction.ignorepinlength=6


phone.stdVariationQuery=select variation from psx_icctx_file_defn_t where ctx_type='IND' and active='Y' and file_id=30 order by variation
phone.mobileVariationQuery=select variation from psx_icctx_file_defn_t where ctx_type='IND' and active='Y' and file_id=29 order by variation

phone.SEPARATORLIST=,-/&
phone.EXTENSIONLIST=EXT,EXTN,O

