server.port=9097
server.servlet.context-path=/im

dmlPrePostFilePath=E:/Prime360_NOVA_Install_13Jul2025/ImportManagerPropertyFiles/
metaDataFilePath=E:/Prime360_NOVA_Install_13Jul2025/ImportManagerPropertyFiles/
controlFilePath=E:/Prime360_NOVA_Install_13Jul2025/ImportManagerPropertyFiles/
logger.homefolder=E:/Prime360_NOVA_Install_13Jul2025/logs
# Log levels
logging.level.root=INFO

# Log file configurations
logging.file.name=logs/im.log
logging.file.max-size=10MB
logging.file.max-history=60


# Console log pattern
logging.pattern.console = %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
												

# File log pattern
logging.pattern.file=%d %p %c{1} [%t] %m%n




