isAddToTargetEnabled=true
inputService.enableAutocommit=true
REQUEST_ID_CHECK=SELECT COUNT(1) FROM PSX_REQUEST WHERE REQUEST_ID=?
AllRestSrcSystemEndpoints=select DATA_SOURCE_NAME src_system,endpoint from md_templates where UPPER(INTEGRATION_TYPE)='NEW_WEBSERVICE'
AllEmployerNamesQuery=select count(*) from EmployerNames where employer_name=?
soaSequenceQuery=SELECT nextval('SOA_REQ_PSXIDBATCHID_SEQUENCE')
allProfileIdsQuery=select profile_id,profile_name from psx_profiles_customer where active='Y'
defaultProfileIdQuery=select profile_id from psx_profiles_customer where upper(profile_name)=upper(?) and active='Y'
insertErrorTable=insert into source_system_error_stats(source,requestid,status,error_message)values(?,?,?,?)
auditInsertQuery=insert into ws_audit(psx_id,requestid,reqmap,srcSystem,purpose,insert_time) values (?,?,?,?,?,current_timestamp)

enableFillersChecking=false
profileName=LOS_PROFILE
CRMXT=CRMXT
isFallbackMechanismEnabled=false
defaultPriority=100
defaultProfile=2
##Special chars
isCleaningEnabled=true
regularExpression=[^\\p{Print}]|[&<>\"']
partitionNumber=p0
IS_TO_AUDIT=true
isATReq=false
isRBResponseToBeEncrypted=false
isToLogRequestandResponse=true


prioritiesString=1,2,3,4,5,6,100
