spring.application.name=Master-Services-ws
server.port=8443
server.servlet.context-path=/masterservice

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
ldapUrl=ldap://192.168.1.256:389
ldap.dn=@posidex.com
cors.origin= http://localhost:4200,http://192.168.1.131:4201,http://localhost:4201,http://192.168.1.131:4200

employerNameReportHeaders=srno,employerName,createdByUserId,createdByUsername,createdUserRole,createdDateTimeStamp,approvedByUserId,ApprovedByUsername,ApprovedDateTimeStamp,approvedUserRole,Action,remarks

defaultRetentionPeriod=7

Reports=E:/RA_HA_HS_12082022
RETENTION_PERIOD_DAY_COUNT=145,7
PriorityListQueueNames=select QUEUE_NAME from PSX_PMWORKERS_CONFIG_T where queue_name in ('PSX_OTHERS_Q','PSX_STRINGENT_Q')
PrimeMatch_Eod_Queue=PSX_PM_EOD_AP_Q
AllQueueNamePurposeQuery=SELECT a.queue_name,  C.PURPOSE_ID FROM service_defn a,  WORKSCOPE_DEFN B,  purpose_defn c WHERE a.service_id=b.service_id AND c.work_id     =b.work_id AND B.WORK_ID    IN  (SELECT work_id FROM purpose_defn WHERE purpose_id IN (801,802,803,804,805,806,807)  )AND A.SERVICE_ID NOT IN (211,500)AND purpose_id       IN (801,802,803,804,805,806,807)
