server.port=9007
server.servlet.context-path=/ml

AUDIT_QUERY=INSERT INTO AUTOVERF_ANALYSIS VALUES(?, ?, ?, ?, ?, ?, systimestamp, ?)


UPDATE_RECORD_STATUS=update REPORT_INPUT_OUTPUT_auto_verf set Ml_decision=? where RECORD_ID=? and requestid=?

ML_AUDIT_QUERY=insert into ML_AUTOVERF_ANALYSIS(ACCEPT_REJECT,INSERT_TS,PSX_ID,REQUESTID,REQUESTJSON,RESPONSEJSON) values(?,current_timestamp,?,?,?,?)
SKIP_RECORD_VALUE=1000
IS_ML_TO_TAKE_DECISION=FALSE
ML_API_NOT_FOUND_ERROR=404 NOT FOUND
ML_API_ERROR=I/O error on POST request
ML_QUEUE_NAME=PSX_ML_AUTOVERF_QUEUE
ML_REPOST_COUNT=3
ML_RIO_AUTOVERF_QRY=SELECT aadhaar_no, accept_reject, accountid, accountowner, addressline, addressline1, addressline2, addressline3, addressline4, age, annualincome, app_id, billingdate, birthdate, blank, borrower_flag, branchid, category, checker_id, checker_status, cibil_score_flag, circlename, city, city1, city2, city3, city4, classfication, client_publish_time, client_report_status, client_report_time, cluster_id, coalesce(col1000strength, 0) AS col1000strength, coalesce(col1020strength, 0) AS col1020strength, coalesce(col2000strength, 0) AS col2000strength, coalesce(col3000strength, 0) AS col3000strength, coalesce(col4000strength, 0) AS col4000strength, coalesce(col1040strength, 0) AS col1040strength, coalesce(col5030strength, 0) AS col5030strength, coalesce(col5040strength, 0) AS col5040strength, coalesce(col5310strength, 0) AS col5310strength, coalesce(col5310strength, 0) AS col1050strength, coalesce(col5310strength, 0) AS col1070strength, coalesce(cs1strength, 0) AS cs1strength, coalesce(cs2strength, 0) AS cs2strength, coalesce(cs2strength, 0) AS cs3strength, coalesce(col1000bmcnt, 0) AS col1000bmcnt, coalesce(col1040bmcnt, 0) AS col1040bmcnt, coalesce(col1050bmcnt, 0) AS col1050bmcnt, coalesce(col1070bmcnt, 0) AS col1070bmcnt, comments, companylegalform, companyname, creation_d, creditcardno, creditmanager_employee_code, creditmanager_employee_name, current_outstanding, custidpart1, custidpart2, custidpart3, custidpart4, custidpart5, customerid, customertype, customeruniqueid, cust_exposure, datasourcename, dayspastdue, days_overline_current, days_overline_ytd, days_overtime, days_past_due, dedupe_category, dedupe_indicator, dedupe_match_count, dedupe_nomatch_count, dedupe_type, dedupe_user_lockedby, deliquencyreason, departmentname, dg_lchg_time, disbursement_date, dsa_code, dunsnumber, effectivedate, email, email1, email2, email3, email4, enquiry_type, entitytype, extra_date_1, extra_date_2, extra_date_3, extra_eq_column1, extra_eq_column10, extra_eq_column11, extra_eq_column2, extra_eq_column3, extra_eq_column4, extra_eq_column5, extra_eq_column6, extra_eq_column7, extra_eq_column8, extra_eq_column9, extra_name_1, extra_name_2, extra_name_3, extra_name_4, facebookid, fathername, file_unique_number, filler_12, filler_17, financial_lchg_time, firstname, gender, grouptype, incomegroup, industry, insta_loan, is_exported, is_locked, is_verified, jigsawid, jobtitle, lastname, lastupdatedate, licenseid, loanamount, loan_status, location_code, lockedby, los_no, martialstatus, matched_source, medicalrecordnumber, middlename, mobile, mothername, mrp, coalesce(name, concat(firstname , '' , middlename , '' , lastname)) name, nationalid, negative_hits, npi, numberofemployees, ordernumber, original_status, otherdate, overdraftcollateraldetails, overdraftlimitno, parentcompanyname, passportid, phone, phone1, phone2, phone3, phone4, pos_match_count, pos_match_reason, pos_match_type, pos_request_status, pos_request_time, pos_response_time, priority, productcode, product_code, programname, promotion, psx_batch_id, psx_batch_id_trg, record_id as psx_id, push_start_time, push_time, rationcard_no, recordcreateddate, recordid, record_assigned_time, record_displayed_time, record_generation_time, record_type, reference_id, relatedname, relatedname1, relatedname2, remarks, requestid, request_posted_time, request_username, rmk_bad_match_count, rmk_good_match_count, rm_employeecode, rm_employeename, role_id, sas_id, sas_id_match_count, segment_name, service_type, sex, siccode, skipped_users, skip_count, sourcename, source_brokerid, spousename, srcsystem_mrp, srcsystem_priority, stage_id, state, state1, state2, state3, state4, status, system_match_count, system_nomatch_count, system_referrel_count, taxid, total_amount_due, total_exposure, total_negative_loan, transactionamount, transactiondate, twitterid, type, ucid, umid, verification_comment, verification_time, verification_user, verifiedby, verified_time, voter_id, website, zipcode, zipcode1, zipcode2, zipcode3, zipcode4, zone_code, to_char(autoverify_initiate_ts, 'dd-MM-yyyy hh24:mi:ss') AS autoverify_initiate_ts, autoverify_processed_ts,strengths FROM report_input_output_auto_verf WHERE requestid = ? AND ( pos_match_type IS NULL OR pos_match_type IN ( 'REFERRAL' ) ) ORDER BY record_type, pos_match_type, psx_id

RSFETCHCOUNT=100

INSERT_INTO_RIO_QRY=INSERT INTO REPORT_INPUT_OUTPUT (AADHAAR_NO,ACCEPT_REJECT,ACCOUNTID,ACCOUNTOWNER,ADDRESSLINE,ADDRESSLINE1,ADDRESSLINE2,ADDRESSLINE3,ADDRESSLINE4,AGE,ANNUALINCOME,APPROVAL_DATE,APP_ID,ATH3_CURR_BAL,ATH3_TOT_AMT_DUE,AUTOVERIFY_INITIATE_TS,AUTOVERIFY_PROCESSED_TS,BILLINGDATE,BIRTHDATE,BLANK,BLOCK_CODE1,BLOCK_CODE2,BORROWER_FLAG,BRANCHID,CATEGORY,CHECKER_ID,CHECKER_STATUS,CIBIL_SCORE_FLAG,CIRCLENAME,CITY,CITY1,CITY2,CITY3,CITY4,CLASSFICATION,CLIENT_PUBLISH_TIME,CLIENT_REPORT_STATUS,CLIENT_REPORT_TIME,CLUSTER_ID,COC_HMLM_STATUS,COL1000BMCNT,COL1000STRENGTH,COL1020STRENGTH,COL1040BMCNT,COL1040STRENGTH,COL1050BMCNT,COL1050STRENGTH,COL1070BMCNT,COL1070STRENGTH,COL2000STRENGTH,COL3000STRENGTH,COL4000STRENGTH,COL5020STRENGTH,COL5030STRENGTH,COL5040STRENGTH,COL5310STRENGTH,COL5340STRENGTH,COL5360STRENGTH,COMMENTS,COMPANYLEGALFORM,COMPANYNAME,CONSTITUTION,CREATION_D,CREDITCARDNO,CREDITLIMIT,CREDITMANAGER_EMPLOYEE_CODE,CREDITMANAGER_EMPLOYEE_NAME,CREDITSEGMENTATION,CS1STRENGTH,CS2STRENGTH,CS3STRENGTH,CS4STRENGTH,CURRENT_OUTSTANDING,CUSTIDPART1,CUSTIDPART2,CUSTIDPART3,CUSTIDPART4,CUSTIDPART5,CUSTOMERID,CUSTOMERNUMBER,CUSTOMERTYPE,CUSTOMERUNIQUEID,CUST_EXPOSURE,DATASOURCENAME,DATE_LAST_OVERLINE,DAYSPASTDUE,DAYS_OVERLINE_CURRENT,DAYS_OVERLINE_YTD,DAYS_OVERTIME,DAYS_PAST_DUE,DEDUPE_CATEGORY,DEDUPE_DATE,DEDUPE_INDICATOR,DEDUPE_MATCH_COUNT,DEDUPE_NOMATCH_COUNT,DEDUPE_TYPE,DEDUPE_USER_LOCKEDBY,DELIQUENCYREASON,DELQ_AMOUNT,DEPARTMENTNAME,DESIGNATION,DEVIATIONLEVEL,DE_DUPE_CAT,DG_LCHG_TIME,DISBURSEMENT_DATE,DSA_CODE,DUNSNUMBER,EFFECTIVEDATE,EMAIL,EMAIL1,EMAIL2,EMAIL3,EMAIL4,EMI,EMI_AMOUNT,EMI_CURR_BAL,EMI_NBR,EMI_TENURE,ENQUIRY_TYPE,ENTITYTYPE,EXTRA_DATE_1,EXTRA_DATE_2,EXTRA_DATE_3,EXTRA_EQ_COLUMN1,EXTRA_EQ_COLUMN10,EXTRA_EQ_COLUMN11,EXTRA_EQ_COLUMN2,EXTRA_EQ_COLUMN3,EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5,EXTRA_EQ_COLUMN6,EXTRA_EQ_COLUMN7,EXTRA_EQ_COLUMN8,EXTRA_EQ_COLUMN9,EXTRA_NAME_1,EXTRA_NAME_2,EXTRA_NAME_3,EXTRA_NAME_4,FACEBOOKID,FATHERNAME,FILE_UNIQUE_NUMBER,FILLER13,FILLER_12,FILLER_17,FILLER_NUMBER_1,FILLER_STRING_4,FINANCIAL_LCHG_TIME,FIRSTNAME,GENDER,GROUPTYPE,GROUP_ID,HIBAL,HMLM_STATUS_COUNT,INCOMEGROUP,INDUSTRY,INSTA_LOAN,IS_EXPORTED,IS_LOCKED,IS_VERIFIED,JIGSAWID,JOBTITLE,LASTNAME,LASTUPDATEDATE,LETTERSENT1,LICENSEID,LN_AMOUT,LN_BOOKED_DT,LOANAMOUNT,LOAN_STATUS,LOCATION_CODE,LOCKEDBY,LOS_NO,MARTIALSTATUS,MATCHED_SOURCE,MEDICALRECORDNUMBER,MIDDLENAME,MIN_AMOUNT_DUE,ML_DECISION,MOBILE,MOTHERNAME,MRP,MT_AMOUNT,MT_COUNT,MT_POSTING_DATE,MT_TXN_CODE,NAME,NATIONALID,NEGATIVE_HITS,NO_OF_MONTHS_DEFAULT,NPI,NUMBEROFEMPLOYEES,ORDERNUMBER,ORIGINAL_STATUS,OTHERDATE,OVERDRAFTCOLLATERALDETAILS,OVERDRAFTLIMITNO,PARENTCOMPANYNAME,PASSPORTID,PENDINGSTAGE,PHONE,PHONE1,PHONE2,PHONE3,PHONE4,POS_MATCH_COUNT,POS_MATCH_REASON,POS_MATCH_TYPE,POS_REQUEST_STATUS,POS_REQUEST_TIME,POS_RESPONSE_TIME,PRIORITY,PRODUCTCODE,PRODUCT_CODE,PRODUCT_NAME,PROGRAMNAME,PROMOTION,PROMO_LOGIC,PSX_BATCH_ID,PSX_BATCH_ID_TRG,PSX_ID,PUSH_START_TIME,PUSH_TIME,RATIONCARD_NO,READ_DATE,READ_FLAG,RECORDCREATEDDATE,RECORDID,RECORD_ASSIGNED_TIME,RECORD_DISPLAYED_TIME,RECORD_GENERATION_TIME,RECORD_ID,RECORD_TYPE,REFERENCE_ID,RELATEDNAME,RELATEDNAME1,RELATEDNAME2,RELATIONSHIP,RELATIONSHIPNUMBER,REMARKS,REQUESTID,REQUEST_POSTED_TIME,REQUEST_USERNAME,RMK_BAD_MATCH_COUNT,RMK_GOOD_MATCH_COUNT,RM_EMPLOYEECODE,RM_EMPLOYEENAME,ROLE_ID,SAS_ID,SAS_ID_MATCH_COUNT,SAS_UPDATE_DATE,SAS_UPDATE_STATUS,SCORE1,SEGMENT_NAME,SERVICE_TYPE,SEX,SICCODE,SKIPPED_USERS,SKIP_COUNT,SOURCECODE,SOURCENAME,SOURCE_BROKERID,SPOUSENAME,SRCSYSTEM_MRP,SRCSYSTEM_PRIORITY,STAGE_ID,STATE,STATE1,STATE2,STATE3,STATE4,STATUS,STRENGTHS,SYSTEM_MATCH_COUNT,SYSTEM_NOMATCH_COUNT,SYSTEM_REFERREL_COUNT,TAXID,TENURE,TOTAL_AMOUNT_DUE,TOTAL_EXPOSURE,TOTAL_NEGATIVE_LOAN,TRANSACTIONAMOUNT,TRANSACTIONDATE,TWITTERID,TYPE,UCID,UMID,VALIDITY_DATE,VERIFICATION_COMMENT,VERIFICATION_TIME,VERIFICATION_USER,VERIFIEDBY,VERIFIED_TIME,VOTER_ID,WEBSITE,WITHDRAW_AMT_SIX,WITHDRAW_AMT_THR,WITHDRAW_CNT_SIX,WITHDRAW_CNT_THR,ZIPCODE,ZIPCODE1,ZIPCODE2,ZIPCODE3,ZIPCODE4,ZONE_CODE ) SELECT  AADHAAR_NO,ACCEPT_REJECT,ACCOUNTID,ACCOUNTOWNER,ADDRESSLINE,ADDRESSLINE1,ADDRESSLINE2,ADDRESSLINE3,ADDRESSLINE4,AGE,ANNUALINCOME,APPROVAL_DATE,APP_ID,ATH3_CURR_BAL,ATH3_TOT_AMT_DUE,AUTOVERIFY_INITIATE_TS,CURRENT_TIMESTAMP,BILLINGDATE,BIRTHDATE,BLANK,BLOCK_CODE1,BLOCK_CODE2,BORROWER_FLAG,BRANCHID,CATEGORY,CHECKER_ID,CHECKER_STATUS,CIBIL_SCORE_FLAG,CIRCLENAME,CITY,CITY1,CITY2,CITY3,CITY4,CLASSFICATION,CLIENT_PUBLISH_TIME,CLIENT_REPORT_STATUS,CLIENT_REPORT_TIME,CLUSTER_ID,COC_HMLM_STATUS,COL1000BMCNT,COL1000STRENGTH,COL1020STRENGTH,COL1040BMCNT,COL1040STRENGTH,COL1050BMCNT,COL1050STRENGTH,COL1070BMCNT,COL1070STRENGTH,COL2000STRENGTH,COL3000STRENGTH,COL4000STRENGTH,COL5020STRENGTH,COL5030STRENGTH,COL5040STRENGTH,COL5310STRENGTH,COL5340STRENGTH,COL5360STRENGTH,COMMENTS,COMPANYLEGALFORM,COMPANYNAME,CONSTITUTION,CREATION_D,CREDITCARDNO,CREDITLIMIT,CREDITMANAGER_EMPLOYEE_CODE,CREDITMANAGER_EMPLOYEE_NAME,CREDITSEGMENTATION,CS1STRENGTH,CS2STRENGTH,CS3STRENGTH,CS4STRENGTH,CURRENT_OUTSTANDING,CUSTIDPART1,CUSTIDPART2,CUSTIDPART3,CUSTIDPART4,CUSTIDPART5,CUSTOMERID,CUSTOMERNUMBER,CUSTOMERTYPE,CUSTOMERUNIQUEID,CUST_EXPOSURE,DATASOURCENAME,DATE_LAST_OVERLINE,DAYSPASTDUE,DAYS_OVERLINE_CURRENT::NUMERIC,DAYS_OVERLINE_YTD::NUMERIC,DAYS_OVERTIME,DAYS_PAST_DUE,DEDUPE_CATEGORY,DEDUPE_DATE,DEDUPE_INDICATOR,DEDUPE_MATCH_COUNT,DEDUPE_NOMATCH_COUNT,DEDUPE_TYPE,DEDUPE_USER_LOCKEDBY,DELIQUENCYREASON,DELQ_AMOUNT,DEPARTMENTNAME,DESIGNATION,DEVIATIONLEVEL,DE_DUPE_CAT,DG_LCHG_TIME,DISBURSEMENT_DATE,DSA_CODE,DUNSNUMBER,EFFECTIVEDATE,EMAIL,EMAIL1,EMAIL2,EMAIL3,EMAIL4,EMI,EMI_AMOUNT,EMI_CURR_BAL,EMI_NBR,EMI_TENURE,ENQUIRY_TYPE,ENTITYTYPE,EXTRA_DATE_1,EXTRA_DATE_2,EXTRA_DATE_3,EXTRA_EQ_COLUMN1,EXTRA_EQ_COLUMN10,EXTRA_EQ_COLUMN11,EXTRA_EQ_COLUMN2,EXTRA_EQ_COLUMN3,EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5,EXTRA_EQ_COLUMN6,EXTRA_EQ_COLUMN7,EXTRA_EQ_COLUMN8,EXTRA_EQ_COLUMN9,EXTRA_NAME_1,EXTRA_NAME_2,EXTRA_NAME_3,EXTRA_NAME_4,FACEBOOKID,FATHERNAME,FILE_UNIQUE_NUMBER,FILLER13,FILLER_12,FILLER_17,FILLER_NUMBER_1,FILLER_STRING_4,FINANCIAL_LCHG_TIME,FIRSTNAME,GENDER,GROUPTYPE,GROUP_ID,HIBAL,HMLM_STATUS_COUNT,INCOMEGROUP,INDUSTRY,INSTA_LOAN,IS_EXPORTED,IS_LOCKED,IS_VERIFIED,JIGSAWID,JOBTITLE,LASTNAME,LASTUPDATEDATE,LETTERSENT1,LICENSEID,LN_AMOUT,LN_BOOKED_DT,LOANAMOUNT,LOAN_STATUS,LOCATION_CODE,LOCKEDBY,LOS_NO,MARTIALSTATUS,MATCHED_SOURCE,MEDICALRECORDNUMBER,MIDDLENAME,MIN_AMOUNT_DUE,ML_DECISION,MOBILE,MOTHERNAME,MRP,MT_AMOUNT,MT_COUNT,MT_POSTING_DATE,MT_TXN_CODE,NAME,NATIONALID,NEGATIVE_HITS,NO_OF_MONTHS_DEFAULT,NPI,NUMBEROFEMPLOYEES,ORDERNUMBER,ORIGINAL_STATUS,OTHERDATE,OVERDRAFTCOLLATERALDETAILS,OVERDRAFTLIMITNO,PARENTCOMPANYNAME,PASSPORTID,PENDINGSTAGE,PHONE,PHONE1,PHONE2,PHONE3,PHONE4,POS_MATCH_COUNT,POS_MATCH_REASON,POS_MATCH_TYPE,POS_REQUEST_STATUS,POS_REQUEST_TIME,POS_RESPONSE_TIME,PRIORITY,PRODUCTCODE,PRODUCT_CODE,PRODUCT_NAME,PROGRAMNAME,PROMOTION,PROMO_LOGIC,PSX_BATCH_ID,PSX_BATCH_ID_TRG,PSX_ID,PUSH_START_TIME,PUSH_TIME,RATIONCARD_NO,READ_DATE,READ_FLAG,RECORDCREATEDDATE,RECORDID,RECORD_ASSIGNED_TIME,RECORD_DISPLAYED_TIME,RECORD_GENERATION_TIME,RECORD_ID,RECORD_TYPE,REFERENCE_ID,RELATEDNAME,RELATEDNAME1,RELATEDNAME2,RELATIONSHIP,RELATIONSHIPNUMBER,REMARKS,REQUESTID,REQUEST_POSTED_TIME,REQUEST_USERNAME,RMK_BAD_MATCH_COUNT,RMK_GOOD_MATCH_COUNT,RM_EMPLOYEECODE,RM_EMPLOYEENAME,ROLE_ID,SAS_ID::NUMERIC,SAS_ID_MATCH_COUNT,SAS_UPDATE_DATE,SAS_UPDATE_STATUS,SCORE1,SEGMENT_NAME,SERVICE_TYPE,SEX,SICCODE,SKIPPED_USERS,SKIP_COUNT,SOURCECODE,SOURCENAME,SOURCE_BROKERID,SPOUSENAME,SRCSYSTEM_MRP,SRCSYSTEM_PRIORITY,STAGE_ID,STATE,STATE1,STATE2,STATE3,STATE4,STATUS,STRENGTHS,SYSTEM_MATCH_COUNT,SYSTEM_NOMATCH_COUNT,SYSTEM_REFERREL_COUNT,TAXID,TENURE,TOTAL_AMOUNT_DUE::NUMERIC,TOTAL_EXPOSURE,TOTAL_NEGATIVE_LOAN,TRANSACTIONAMOUNT,TRANSACTIONDATE,TWITTERID,TYPE,UCID,UMID,VALIDITY_DATE,VERIFICATION_COMMENT,VERIFICATION_TIME,VERIFICATION_USER,VERIFIEDBY,VERIFIED_TIME,VOTER_ID,WEBSITE,WITHDRAW_AMT_SIX,WITHDRAW_AMT_THR,WITHDRAW_CNT_SIX,WITHDRAW_CNT_THR,ZIPCODE,ZIPCODE1,ZIPCODE2,ZIPCODE3,ZIPCODE4,ZONE_CODE  FROM report_input_output_auto_verf WHERE REQUESTID=?

ML_UPDATE_INPUT_RECORD_STATUS=UPDATE REPORT_INPUT_OUTPUT_AUTO_VERF SET Accept_Reject= CASE WHEN Record_Type='INPUT' THEN CASE WHEN (system_match_count=0) THEN 'NOMATCH' ELSE 'MATCH' END ELSE 'NM' END, VERIFIEDBY=-1, VERIFIED_TIME =current_timestamp, VERIFICATION_COMMENT='POS_ML', VERIFICATION_USER='POS_ML', IS_VERIFIED ='Y' WHERE Requestid =? AND coalesce(ACCEPT_REJECT,'0') !='SM'

INPUT_DATA_SOURCE_QUERY=select entitytype,is_verified,mrp,priority from  report_input_output where requestid=? and record_type='INPUT'

ML_ERROR_COUNT_CHECK_QUERY=select count(*) from ML_AUTOVERF_ERROR where requestid=?

LOAD_PROFILE_WISE_RULES_QUERY=SELECT PARAMCODE,COLUMNNAME FROM psx_profile_parameters_customer WHERE Active='Y' and UI_PARAMETER_NAME IN(<<>>)

LOAD_PROFILE_WISE_MATCHRULES_QUERY=select MATCHING_RULE_CSV from psx_profiles_customer where active='Y' and profile_id=?

LOAD_PROFILE_ID_QUERY=select profile_name,profile_id from psx_profiles_customer where Active='Y' order by profile_id

LOAD_ML_INTEGRATION_COLUMNS=select column_name,param_code from psx_ml_Integration_columns order by poistion asc

ML_ADDR_STRENGTH=60

ML_CS_STRENGTH=1

IS_REQUIRED_AUDIT=true

ML_BATCH_UPDATE_COUNT=20

ML_ERROR_AUDIT_QUERY=insert into ML_AUTOVERF_ERROR(INSERT_TS,PSX_ID,REQUESTID,DESCRIPTION) values(current_timestamp,?,?,?)

DELETE_FROM_RIO_AUTO_VERF=DELETE FROM REPORT_INPUT_OUTPUT_AUTO_VERF WHERE REQUESTID=?

GET_ALL_SOURCE_SYSTEMS=select INTEGRATION_TYPE from md_templates where is_push='Y' and DATA_SOURCE_NAME=?

ML_PRMVERHEADER=RecordId{UseCase:1}$NT_{lvl:3,tmp:0.45,column_name:Name}$NT_{lvl:3,tmp:0.45,column_name:LastName}$NT_{lvl:3,tmp:0.45,column_name:EmployerName}$NT_{lvl:3,tmp:0.45,column_name:ExtraName4}$DT_{type:1,column_name:DOB}$PhT_{criteria:1,column_name:residence_phone,matchPer:50}$PhT_{criteria:1,column_name:office_phone,matchPer:30}$PhT_{criteria:1,column_name:mobile,matchPer:30}$AT_{AddrCityPinCriteria:1,AMP:60,BaseLinePercentage:1,CSEquation:AS=70;HNO=30;HNONULL=0;BaseLineForCS=2;CV=0=>AS=60;HNO=40;HNONULL=0;BaseLineForCS=2;CV=-5=>AS=80;HNO=20;HNONULL=0;BaseLineForCS=2;CV=0,column_name:resAddress}$AT_{AddrCityPinCriteria:1,AMP:60,BaseLinePercentage:1,CSEquation:AS=70;HNO=30;HNONULL=0;BaseLineForCS=2;CV=0=>AS=60;HNO=40;HNONULL=0;BaseLineForCS=2;CV=-5=>AS=80;HNO=20;HNONULL=0;BaseLineForCS=2;CV=0,column_name:offAddress}$ET_{column_name:email}$ET_{column_name:email1}$ET_{column_name:bank_acnt_name}$ET_{column_name:bank_acnt_no}



logger.homefolder=logs
# Log levels
#logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Log file configurations
logging.file.name=logs/ml.log
logging.file.max-size=10MB
logging.file.max-history=60

# Console log pattern
logging.pattern.console = %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# File log pattern
logging.pattern.file=%d %p %c{1} [%t] %m%n

name.level=3
name.tokenMatchPercentage=0.45
name.cNPDiff=10
name.relaxBigMatch=false
name.inverseMatchByBigFactor=0.9
name.ignoreSecondCharSound=false
name.cMatchSuper=0.45
name.dynamicMatchSuper=false
name.cMatchByBig=0.77
name.cMatchCum= 1.7
name.cMatchRatio=0.8637
name.cMatchBigRatio= 0.7878
name.cMatchSlope=1
name.cMatchExp=1
name.phoneticDegree=2
name.cMatchContinuous=true
name.cHashVersion=0
name.cMatchBackward=false
name.cNameMatchLevel=3
name.cTokenInitStrength= 0.5
name.cInitInitStrengthCase1=1
name.cInitInitStrengthCase2=1
name.mValue= 2.414213562373095
name.highPhonetic=true
name.relaxPattern=false
name.applyTightSound=true
name.smallBigComparison=true
name.smallSmallComparison=true
name.disablePhoneticDegreeIncrementByOne=false
name.parameterName=NAME
name.cleaningContextNumber=1
name.algorithmtruthMatrices=""
name.responseConsistsOfInput=false
name.algorithmNumber=0

phone.parameterName=PHONE
phone.cleaningContextNumber=1
phone.matchThresholdStrength=50
phone.responseConsistsOfInput=false


dob.level=4
dob.cleaningContextNumber=1
dob.parameterNameForCleaning=DOB
dob.matchStrength=0
dob.responseConsistsOfInput=false


equality.cleaningContextNumber=1
equality.responseConsistsOfInput=false
equality.parameterNameForCleaning=PAN

address.parameterNameForCleaning=ADDRESS
address.baseLinePercentage=1
address.cleaningContextNumber=1
address.matchThresholdStrength=50
address.responseConsistsOfInput=false
address.hno.1=30
address.as.1=70
address.hnonull.1=0
address.cv.1=0
address.baseLineForCS.1=2

address.hno.2=40
address.as.2=60
address.hnonull.2=0
address.cv.2=-5
address.baseLineForCS.2=2

address.hno.3=20
address.as.3=80
address.hnonull.3=0
address.cv.3=0
address.baseLineForCS.3=2

user.userId=Admin1
user.isPlainPassword=true
user.isRelogin=true
user.password=Ptpl!234



PRIMEVER.url=http://192.168.5.150:80/primever
ML_INTEGRATION_URI=http://192.168.1.210:500
noofworkers=1
