# Port used when deploying the application as a WAR file on an external Tomcat server
server.port=8443
# Uncomment the below line to use this port when running the application as a JAR
# server.port=2567
server.servlet.contextPath=/operations
management.endpoints.web.exposure.include=health
logging.file.name=${commonPathForAllServices}/logs/Operations.log
readTimeout=5000
connectTimeout=5000