server.port=2489
server.servlet.contextPath=/hof

isRIDFileEncrypted=false

request.dataBundle.encrypt.secretKey=RVT0iR+9EIMuPqjyx253N5g9CiBwCYUnGpBcoMDZ8w8v0h4zuflQXG/GwkWpntc7/BbGSyX0n19gW2j5
response.dataBundle.encrypt.secretKey=5Hm7/aWL6138og5xAK56bKAwD+YH3vZTReaSmQ6ONRSt0GlwIwFEt6HAq65UXNApTc/zMSmfD0fJfQxo

management.endpoints.web.exposure.include=health
microservice.number=0

minimum.memory=64
maximum.memory=1024
cleaningImplementorClassName=posidex.prime360.engine.cleaning.NullContextCleaningImplementor
isCacheServerAvailable=false

buildNumber=1
buildDate=2025-06-04

logging.config=http://localhost:2458/primehof/default/master/logback_hof-spring.xml