server.port=2469
server.servlet.contextPath=/engine


isRIDFileEncrypted=true

request.dataBundle.encrypt.secretKey=41N81bIBapXt1OlLQ5+iGqq6BXcM5k1BRjsmATSs1rixX5zM7F4yqc0aek7vtF9EHzaKBIXAk3UFvOyy
response.dataBundle.encrypt.secretKey=AsNBJzHyx/+IhBY27VlW5GDFycARmzArzMXV7Nu0/NEwE3SMn7XwmoSjDV6IULwjoweqmC/CrL2T2LNw

management.endpoints.web.exposure.include=health
microservice.number=0
startupWithEmptyTenant=true

minimum.memory=64
maximum.memory=1024
cleaningImplementorClassName=posidex.prime360.engine.cleaning.NullContextCleaningImplementor
isCacheServerAvailable=false

buildNumber=1
buildDate=2025-06-04

logging.config=http://localhost:2458/primeapi/default/master/logback_primeapi-spring.xml			