server.port=9092
server.servlet.context-path=/pub


requestStatusCheckingQuery=SELECT is_verified FROM mstr_psx_dg_blk_request b LEFT OUTER JOIN report_input_output a ON a.requestid = b.psx_id::VARCHAR AND a.record_id = b.psx_id WHERE upper(b.cust_id_part_5) = ?  and  upper(b.cust_id_part_4)=?
AllRestSrcSystemEndpoints=select DATA_SOURCE_NAME src_system,endpoint from md_templates where UPPER(INTEGRATION_TYPE)='NEW_WEBSERVICE'

#connection pool config
spring.datasource.maxTotal=10
spring.datasource.maxIdle=4
spring.datasource.maxStatements=5
spring.datasource.minIdle=2
spring.datasource.inactivityTimeOut=5000

spring.datasource.initiallimit=2

enableAutocommit=true
logger.homefolder=logs
# Log levels
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Log file configurations
logging.file.name=logs/publishservice.log
logging.file.max-size=10MB
logging.file.max-history=60

# Console log pattern
logging.pattern.console = %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# File log pattern
logging.pattern.file=%d %p %c{1} [%t] %m%n

dataTimeFormat=dd-MM-yyyy HH:mm:ss:SSS
serviceNameinShort=pub


