#RA
insertResults.limitRefreshPeriodInMillis=60000
insertResults.limitForThePeriod=100
insertResults.timeoutDurationInMillis=25

aggregateResults.limitRefreshPeriodInMillis=60000
aggregateResults.limitForThePeriod=100
aggregateResults.timeoutDurationInMillis=25

updateAtRequestNodes.limitRefreshPeriodInMillis=60000
updateAtRequestNodes.limitForThePeriod=100
updateAtRequestNodes.timeoutDurationInMillis=25

updateAtRequest.limitRefreshPeriodInMillis=60000
updateAtRequest.limitForThePeriod=100
updateAtRequest.timeoutDurationInMillis=25


getRequestIdsPostedToday.limitRefreshPeriodInMillis=60000
getRequestIdsPostedToday.limitForThePeriod=500
getRequestIdsPostedToday.timeoutDurationInMillis=25

moveResultsToAuditTables.limitRefreshPeriodInMillis=60000
moveResultsToAuditTables.limitForThePeriod=100
moveResultsToAuditTables.timeoutDurationInMillis=25

#PrimeAPI
searchRequest.limitRefreshPeriodInMillis=60000
searchRequest.limitForThePeriod=100
searchRequest.timeoutDurationInMillis=25

addToTarget.limitRefreshPeriodInMillis=60000
addToTarget.limitForThePeriod=100
addToTarget.timeoutDurationInMillis=25

#RB
submitRequest.limitRefreshPeriodInMillis=60000
submitRequest.limitForThePeriod=100
submitRequest.timeoutDurationInMillis=25

intradayProcess.limitRefreshPeriodInMillis=60000
intradayProcess.limitForThePeriod=100
intradayProcess.timeoutDurationInMillis=25

bulkQuery.limitRefreshPeriodInMillis=60000
bulkQuery.limitForThePeriod=100
bulkQuery.timeoutDurationInMillis=25

bulkAddToTarget.limitRefreshPeriodInMillis=60000
bulkAddToTarget.limitForThePeriod=100
bulkAddToTarget.timeoutDurationInMillis=25

repushIntraDay.limitRefreshPeriodInMillis=60000
repushIntraDay.limitForThePeriod=100
repushIntraDay.timeoutDurationInMillis=25

queryAndAddToTarget.limitRefreshPeriodInMillis=60000
queryAndAddToTarget.limitForThePeriod=100
queryAndAddToTarget.timeoutDurationInMillis=25

identitySearchRequest.limitRefreshPeriodInMillis=60000
identitySearchRequest.limitForThePeriod=100
identitySearchRequest.timeoutDurationInMillis=25

moveRequestsToAuditTables.limitRefreshPeriodInMillis=60000
moveRequestsToAuditTables.limitForThePeriod=100
moveRequestsToAuditTables.timeoutDurationInMillis=25

#clustering

doPartClustering.limitRefreshPeriodInMillis=60000
doPartClustering.limitForThePeriod=100
doPartClustering.timeoutDurationInMillis=25

doClipClosure.limitRefreshPeriodInMillis=60000
doClipClosure.limitForThePeriod=100
doClipClosure.timeoutDurationInMillis=25

appendStrengthFilterFilesNonClusteringUseCases.limitRefreshPeriodInMillis=60000
appendStrengthFilterFilesNonClusteringUseCases.limitForThePeriod=100
appendStrengthFilterFilesNonClusteringUseCases.timeoutDurationInMillis=25

strengthFilterNonClusteringUseCases.limitRefreshPeriodInMillis=60000
strengthFilterNonClusteringUseCases.limitForThePeriod=100
strengthFilterNonClusteringUseCases.timeoutDurationInMillis=25



#clipapi

clipProcess.limitRefreshPeriodInMillis=60000
clipProcess.limitForThePeriod=100
clipProcess.timeoutDurationInMillis=25

persistTheStateOfTheObject.limitRefreshPeriodInMillis=60000
persistTheStateOfTheObject.limitForThePeriod=100
persistTheStateOfTheObject.timeoutDurationInMillis=25

#automerge
automerge.limitRefreshPeriodInMillis=60000
automerge.limitForThePeriod=100
automerge.timeoutDurationInMillis=25
