#spring.profiles.active=dev
#logging.level.root=warn
#logging.file.name=logs/appDev.log


#give "rrr" to accept request from rrr or "requestBuilder"
request.source=rb

#webClient or restTemplate
rest.calling.service=webClient

#Kafka Properties ######################
kafka.bootstrap-servers=192.168.1.189:9092
#kafka.bootstrap-servers=192.168.4.99:19092,192.168.4.99:29092,192.168.4.99:39092
kafka.replication.factor=3


server.port=8081

Request.Response.WaitTimeInSeconds=30

# Kafka Topics
priority_topic_count=3
priority_topic_partiton_limit=10
kafka-reply-topic=REPLY_TOPIC
kafka-reply-topic-count=4
kafka_general_topic=GENERAL_TOPIC
consumers_logickeys=PRIORITYTOPICSCONSUMER,MULTICACHEBEANCONSUMERSEARCH,MULTICACHEBEANCONSUMERADDTARGET
kafka.consumer.group-id=RRR
kafka-reply-topic-consumers=10
#cahce bean names
cache.beans.names=Customer,Propex
cache.beans.engine-partitions=3,3

#single cachebean
#cache.beans.names=Customer
#cache.beans.engine-partitions=3

request-builder.requestTypes=Query,AddToTarget,QueryAddToTarget



##cache bean topic names and partitions created by RB   
#cache.beans.topics.search=PSX_Customer_Requests_4,PSX_Propex_Requests_4
#cache.beans.partitions.search=2,1
#cache.beans.topics.addtarget=PSX_Customer_AT_Request_4,PSX_Propex_AT_Request_4
#cache.beans.partitions.addtarget=1,1

#cache bean topic names and partitions created by RB   
cache.beans.topics.search=PSX_Customer_Requests_4
cache.beans.partitions.search=2
cache.beans.topics.addtarget=PSX_Customer_AT_Request_4,PSX_Propex_AT_Request_4
cache.beans.partitions.addtarget=4,4
cache.beans.consumers.addtarget=4,4
cache.beans.topics=PSX_Customer_Requests_1,PSX_Customer_Requests_2,PSX_Customer_Requests_3,PSX_Customer_Requests_4,PSX_Customer_Requests_5,PSX_Customer_Requests_6,PSX_Customer_Requests_100,PSX_Propex_Requests_4
cache.beans.partitions=10,6,4,2,2,2,6,4
cache.beans.consumers=10,6,4,2,2,2,6,4

#single cachebean
#cache.beans.topics.search=PSX_Customer_Requests_4
#cache.beans.partitions.search=2
#cache.beans.topics.addtarget=PSX_Customer_AT_Request_4
#cache.beans.partitions.addtarget=1

#for hdfc purpose
#cache.beans.topics=PSX_Customer_Requests_1,PSX_Customer_Requests_2,PSX_Customer_Requests_3,PSX_Customer_Requests_4,PSX_Customer_Requests_5,PSX_Customer_Requests_6,PSX_Customer_Requests_100
#cache.beans.partitions=10,6,4,2,2,2,6

#each cache bean topic priem api urls
#cache.beans.Customer.prime-api.urls=localhost:2469/engine,localhost:2470/engine,localhost:2471/engine
#cache.beans.Customer.prime-api.urls=192.168.1.180:2469,192.168.1.180:2470,192.168.1.180:2471
cache.beans.Customer.prime-api.urls=192.168.1.180:2469,192.168.1.180:2470,192.168.1.180:2471
#cache.beans.Customer.prime-api.urls=a88a4d664313d4692994a3aa221d9ecf-93b4f9ef23655556.elb.ap-south-1.amazonaws.com/engine0,a88a4d664313d4692994a3aa221d9ecf-93b4f9ef23655556.elb.ap-south-1.amazonaws.com/engine1,a88a4d664313d4692994a3aa221d9ecf-93b4f9ef23655556.elb.ap-south-1.amazonaws.com/engine2
cache.beans.Propex.prime-api.urls=localhost:2469,localhost:2470,localhost:2471
#primeapi urls for addtarget
#cache.beans.Customer.addtarget.prime-api.urls=localhost:2469/engine,localhost:2470/engine,localhost:2471/engine
cache.beans.Customer.addtarget.prime-api.urls=primeapip0,primeapip1,primeapip2
cache.beans.Propex.addtarget.prime-api.urls=localhost:2469,localhost:2470,localhost:2471

#-------------------------





# # API URLs
api.protocol=http://
api.request-builder.host=localhost
api.request-builder.port=2468
api.result-processor.host=localhost
api.result-processor.port=2024
api.icc.host=localhost
api.icc.port=2569

#4.99
#api.request-builder.host=192.168.4.99
#api.request-builder.port=2468
#api.result-processor.host=192.168.4.99
#api.result-processor.port=2024


#prime.engine.partitions=1


###urls paths
api.request-builder.search.path=/rb/requestPosting/submit{sourceSystemName}Query
api.request-builder.addTarget.path=/rb/requestPosting/submit{sourceSystemName}AddToTarget
api.request-builder.searchAddTarget.path=/rb/requestPosting/submit{sourceSystemName}QueryAndAddToTarget
api.request-builder.areYouInReadyState=/rb/requestPosting/areYouInReadyState

#api.icccleaning.single.record=/icc/prime360iccleaning/singleRecordCleaningCustomer
api.icccleaning.single.record=/icc/prime360iccleaning/singleRecordCleaning{sourceSystemName}
api.prime-api.search.path=/engine/primeapi/searchRequest
api.prime-api.addTarget.path=/engine/primeapi/addTarget
api.prime-api.areYouInReadyState=/engine/primeapi/areYouInReadyState

api.result-processor.insertResults.path=/ra/insertResults
api.result-processor.aggregateResults.path=/ra/aggregateResults
api.result-processor.updateAtRequestNodes.path=/ra/updateAtRequestNodes
api.result-processor.updateAtRequestStatus.path=/ra/updateAtRequest
api.result-processor.areYouInReadyState=/ra/areYouInReadyState

api.result-processor.getResultsByRequestId.path=/ra/getResultsByRequestId

api.request-builder.query.header.isRBRequestEncrypted = false
api.request-builder.query.header.isRBResponseToBeEncrypted = false
api.request-builder.query.header.isToLogRequestandResponse = false

api.request-builder.addTarget.header.isRBRequestEncrypted = false
api.request-builder.addTarget.header.isRBResponseToBeEncrypted = false
api.request-builder.addTarget.header.isToLogRequestandResponse = false

api.prime-api.header.search.isPrimeAPIRequestEncrypted = false
api.prime-api.header.search.isPrimeAPIResponseToBeEncrypted = false
api.prime-api.header.search.isToLogRequestandResponse = true

api.prime-api.header.addTarget.isPrimeAPIRequestEncrypted = false
api.prime-api.header.addTarget.isPrimeAPIResponseToBeEncrypted = false
api.prime-api.header.addTarget.isToLogRequestandResponse = true

api.result-processor.insert-Results.header.isRARequestEncrypted = false
api.result-processor.insert-Results.header.isRAResponseToBeEncrypted = false
api.result-processor.insert-Results.header.isToLogRequestandResponse = false

api.result-processor.update-Status.header.isRARequestEncrypted = false
api.result-processor.update-Status.header.isRAResponseToBeEncrypted = false
api.result-processor.update-Status.header.isToLogRequestandResponse = false

api.result-processor.updateAtRequestNodes.header.isRARequestEncrypted = false
api.result-processor.updateAtRequestNodes.header.isRAResponseToBeEncrypted = false
api.result-processor.updateAtRequestNodes.header.isToLogRequestandResponse = false

api.result-processor.updateAtRequest.header.isRARequestEncrypted = false
api.result-processor.updateAtRequest.header.isRAResponseToBeEncrypted = false
api.result-processor.updateAtRequest.header.isToLogRequestandResponse = false


#User request fields--------
#common and mandatory fields
request.requestId=requestId
request.profileId=profileId_Customer

#fields used by rrr
correlationId.field=correlationId
skipInsertUpdateResultsField=skipInsertUpdate
hostAddress.field=hostAddress

rrrData.field=rrr_DATA


#beforePrimeApi.requestPath=http://192.168.3.104:2468/rb/requestPosting/callLatchDown
############### RESPONSE HANDLER ###########################
afterUpdateRequest.requestPath=http://localhost:9096/rpmlb/mediator/push/requestId
request.type=String
Input=$requestID

#request parts types for validation of request
request.Customer.Datafields=psx_DG_BLK,psx_ACE_BLK
request.Propex.Datafields=psx_PX_BLK
#request location where rrr_DATA field exist in metatables
rrrData.Customer.requestPath=rpt
rrrData.Propex.requestPath=px

#request.PSX_DG=psx_DG_BLK
#request.PSX_ACE=psx_ACE_BLK
#request.PSX_RPT=psx_RPT_BLK

request.PSX_DG=dg
request.PSX_ACE=ace
request.PSX_RPT=rpt
request.PSX_PX=px



#----------------------------


# Cache Refresh
cache.refresh.rate=300000

#thread pool size
thread.pool.core-size=400
thread.pool.max-size=400
#thread.pool.keep-alive-seconds=60



# Hibernate
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:postgresql://192.168.3.251:5432/prime360c1?stringtype=unspecified
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=prime360user
spring.datasource.password=psx123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=50
#spring.datasource.hikari.minimum-idle=5

webClient.conectionPool.maxConnections=500
webClient.conectionPool.idleTimeoutSeconds=30
webClient.conectionPool.lifetimeSeconds=60
webClient.conectionPool.connectTimeoutMillis=10000
webClient.conectionPool.readTimeoutSeconds =30
webClient.conectionPool.writeTimeoutSeconds=30 									  

#spring.datasource.url=jdbc:postgresql://192.168.1.68:55432/workflow
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgress
#spring.datasource.password=postgress
#spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=jdbc:oracle:thin:@192.168.1.148:1524:pdborcl
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.username=RRR
#spring.datasource.password=psx123
#spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:db2://192.168.3.42:50000/RRR
#spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
#spring.datasource.username=db2inst1
#spring.datasource.password=Ptpl!234
#spring.jpa.hibernate.ddl-auto=update



# Health
management.endpoints.web.exposure.include=health
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoint.health.show-details=always

prime-api.expectingNonZeroOffline=true
prime-api.expectingNonZeroOnline=false

CustomermatchingProcess=3
PropexmatchingProcess=3
CustomerintraDayProcess=1
PropexintraDayProcess=1
CustomerPropexmatchingProcess=6
CustomerPropexintraDayProcess=2
PropexCustomermatchingProcess=6
PropexCustomerintraDayProcess=2


#Activemq Artemis
spring.artemis.mode=native
spring.artemis.broker-url=tcp://192.168.3.102:61616
spring.artemis.user=admin
spring.artemis.password=admin
artemis.management.url=http://192.168.3.102:8161/console/jolokia
artemis.management.user=admin
artemis.management.password=admin
artemis.priority.logic=true


message.broker.types=kafka
#kafka,activemq
ActiveMq.consumers.logicKeys=REPLYTOPICSCONSUMER,ACTIVEMQMULTICACHEBEANCONSUMERSEARCH,ACTIVEMQMULTICACHEBEANCONSUMERADDTARGET

cache.beans.queues.search=PSX_Customer_Requests_1,PSX_Customer_Requests_2,PSX_Customer_Requests_3,PSX_Customer_Requests_4,PSX_Customer_Requests_5,PSX_Customer_Requests_6,PSX_Customer_Requests_100
cache.beans.queues.search.consumers=1,1,1,1,1,1,1
cache.beans.queues.addtarget=PSX_Customer_AT_Requests_4
cache.beans.queues.addtarget.consumers=1
priority.cache.beans.queues.addtarget=PSX_Customer_AT_Request,PSX_Propex_AT_Request
priority.cache.beans.queues.addtarget.consumers=3,3
priority.cache.beans.queues.search=PSX_Customer_Requests,PSX_Propex_Requests
priority.cache.beans.queues.search.consumers=3,3
spring.jms.pub-sub-domain=true

request.message.broker=kafka

priorityColumnName=rpt_FILLER_COLUMN_1

activemq.reply.queue=REPLY_QUEUE
activemq.reply.queue.consumer=3
callable.thread.pool.size=20

#deployment.type=kubernetes

isKafkaEnabled=true
isActiveMQEnabled=false

icccleaningEnabled=true
isSaslEnabled=false
