# Port used when deploying the application as a WAR file on an external Tomcat server
server.port=2468
# Uncomment the below line to use this port when running the application as a JAR
# server.port=2468
server.servlet.contextPath=/rb
maxPeCount=5
spring.kafka.bootstrap-servers=192.168.1.189:9092
#spring.kafka.streams.bootstrap-servers=192.168.1.227:9189
#spring.kafka.consumer.bootstrap-servers=192.168.1.227:9189
messageToBeSentTo=restApi
#kafka,jms,restApi
amqMaxConnections=10
jms.url=tcp://localhost:61616?wireFormat.maxInactivityDuration=0&jms.prefetchPolicy.queuePrefetch=1
requestTimeOutMillis=1
spring.jpa.hibernate.ddl-auto=validate
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=6m
pagination.pageSize=10000
management.endpoints.web.exposure.include=health
threshold=10
thresholdPercentage=10
#profile.maxResultCount.1=5000
#profile.maxRetrievalCount.1=2147483647
microservice.number=0
request.dataBundle.encrypt.secretKey=OVelR7hdPDtjvVt+QRcmegrO3QTL9Ldhf9XIfBhzBxr7B55Oi4ED9sut2i7/EN0D/36YetDZ6LTKcnhW
response.dataBundle.encrypt.secretKey=U9EOVrPPn0SzN7vY/ggkMmAzXs4Lxe6peNYi9iOVvwRln6i4rfscmlsokZHiEvO20QQF+Z9IdmUxwb84

#0-ORACLE,
#1-MYSQL,
#2-SQLSERVER,
#3-H2,
#4-DB2,
#5-TIBERO,
#6-POSTGRESQL

#FOR UTC
offline.dateTimeConversionTypeFromSelection.0=2000
offline.dateTimeConversionTypeFromSelection.1=0
offline.dateTimeConversionTypeFromSelection.2=2000
offline.dateTimeConversionTypeFromSelection.3=-330
offline.dateTimeConversionTypeFromSelection.4=0
offline.dateTimeConversionTypeFromSelection.5=0
offline.dateTimeConversionTypeFromSelection.6=2000

#FOR IST
#offline.dateTimeConversionTypeFromSelection.0=0
#offline.dateTimeConversionTypeFromSelection.1=0
#offline.dateTimeConversionTypeFromSelection.2=2000
#offline.dateTimeConversionTypeFromSelection.3=-330
#offline.dateTimeConversionTypeFromSelection.4=0
#offline.dateTimeConversionTypeFromSelection.5=0
#offline.dateTimeConversionTypeFromSelection.6=2000


management.endpoints.web.exposure.include=health

minimum.memory=64
maximum.memory=1024

buildNumber=1
buildDate=2025-06-04
#mcb request Mappings 
#Customer_Input=NAME_IN_INPUT_NAME,
#Input_Customer=INPUT_NAME_IN_NAME,

logging.config=http://localhost:2458/requestbuilder/default/master/logback_rb-spring.xml
dataTimeFormat=dd-MM-yyyy HH:mm:ss:SSS
serviceNameinShort=RB
IsToAccommodateAdditionalMatches=false
getMultiEqualityProcCall=CALL get_multi_equality(?)
noOfPartitions=3
