server.port=9096
server.servlet.context-path=/rpmlb

resultPush.serviceName=ResultPushService
resultPush.url=http://localhost:9095/push/result-push-service
bot.serviceName=BotService
bot.url=http://localhost:9009/bot
ml.serviceName=MLService
ml.url=http://localhost:9007/ml

enableAutocommit=true

kafka.topic.name1=PSX_RESULT_PUSH_TOPIC
kafka.topic.name2=PSX_ML_AUTOVERF_TOPIC
kafka.topic.name3=psx_bot_service_topic

REQUEST_ID_CHECK_IN_RIO=SELECT count(1) from report_input_output where FILE_UNIQUE_NUMBER=? and record_type='INPUT';

REQUEST_ID_CHECK_IN_RIO_AUTO_VERF=SELECT count(1) from report_input_output_auto_verf where FILE_UNIQUE_NUMBER=? and record_type='INPUT'

SET_RECORD_ID=SELECT psx_id FROM psx_report_input_output_customer WHERE request_id =? and  record_type='INPUT';

WS_Or_T_CHECK=SELECT POS_MATCH_TYPE, FILE_UNIQUE_NUMBER, CUSTIDPART2, POS_MATCH_COUNT, ENTITYTYPE, PRIORITY, MRP, CASE WHEN ENTITYTYPE IN (SELECT DATA_SOURCE_NAME FROM MD_TEMPLATES WHERE integration_type IN ('WEBSERVICE', 'NEW_WEBSERVICE') AND is_push = 'Y') THEN 'WS_SRCS' WHEN ENTITYTYPE IN (SELECT DATA_SOURCE_NAME FROM MD_TEMPLATES WHERE integration_type = 'TABLE' AND is_push = 'Y') THEN 'T_SRCS' ELSE 'UNKNOWN' END AS SRC_FLAG, accept_reject FROM REPORT_INPUT_OUTPUT WHERE RECORD_TYPE = 'INPUT' AND ENTITYTYPE IN (SELECT DATA_SOURCE_NAME FROM MD_TEMPLATES WHERE UPPER(integration_type) IN ('TABLE', 'WEBSERVICE', 'NEW_WEBSERVICE') AND is_push = 'Y') AND REQUESTID = ?;



MAX_REF_COUNT_GTT=SELECT COUNT(*) FROM REPORT_INPUT_OUTPUT_GTT WHERE POS_MATCH_TYPE='REFERRAL';

MAX_REF_COUNT=SELECT BUFFER_COUNT FROM PSX_ROBO_ENABLED;

QUERY_FOR_AUTO_VERFICATION_TYPE=SELECT auto_verification_type FROM PSX_ROBO_PRODUCTS WHERE prdtcode IN (SELECT UPPER(Product_code) FROM report_input_output_gtt WHERE record_type = 'INPUT' and custidpart5=?);

QUERY_FOR_PRIORITY_FROM_AUTO_VERF=SELECT priority from report_input_output_auto_verf where FILE_UNIQUE_NUMBER=? and record_type='INPUT';



logger.homefolder=logs
# Log levels
#logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Log file configurations
logging.file.name=logs/rpmlb.log
logging.file.max-size=10MB
logging.file.max-history=60

# Console log pattern
logging.pattern.console = %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# File log pattern
logging.pattern.file=%d %p %c{1} [%t] %m%n


commonPathForAllServices=F:/PrimeCloud/rpmlb



REQUEST_ID_TYPE_IN_PSX_REQUEST=SELECT request_type FROM PSX_REQUEST WHERE request_id=?;
FIND_PSX_ID_IN_PRIO=SELECT psx_id from PSX_REPORT_INPUT_OUTPUT_CUSTOMER WHERE request_id=? and record_type='INPUT';