server.port=9098
server.servlet.context-path=/servicewrapper

spring.jpa.hibernate.ddl-auto=validate


FINEOD_POST_DML_PROC=CALL psx_fin_merge_report(?)
BULK_QUERY_POST_DML_PROC=CALL PM_SRC_TRG_LINK_BATCH(?,?)
BulkRequestCountCheckQuery=SELECT COUNT(*) FROM PSX_REQUEST WHERE PSX_BATCH_ID=?
RequestStatusCheckQuery=SELECT COUNT(*) FROM PSX_REQUEST WHERE PSX_BATCH_ID=? AND REQUEST_STATUS IN ('C','E')
requestStatusCheckSleepTime=15000
isToWaitAfterBulkQuery=true
EachRequesWaitingTimeMillis=5000


###### SuccessFileGeneration Properties #####

DG_PURPOSE_ID=GENERALEOD
FIN_PURPOSE_ID=FINANCIALEODPROCESS
UCIC_PURPOSE_ID=UCIC_UPDATE
PURGE_PURPOSE_ID=ENGINEPURGING
FIN_UPLOAD_PURPOSE_ID=FINANCIALEOD

BPM_CLIENT_MESSAGE_PROCESS_STATUS_FILE_LOCATION_DG=E:/RA_HA_HS_23112023/logs/GENERALEOD_STATUS/
BPM_CLIENT_MESSAGE_PROCESS_STATUS_FILE_LOCATION_FINANCIAL=E:/RA_HA_HS_23112023/logs/Financial_status/
BPM_CLIENT_MESSAGE_PROCESS_STATUS_FILE_LOCATION_UCIC=E:/RA_HA_HS_23112023/logs/UCIC_STATUS/
BPM_CLIENT_MESSAGE_PROCESS_STATUS_FILE_LOCATION_PURGING=E:/RA_HA_HS_23112023/logs/Purging_STATUS/

#### SSH for success file gen fin eod ####

secondaryServerUserName=administrator
secondaryServerIpaddress=192.168.4.227
secondaryServerPassword=rV1hj/eBiet5LTa2bqNyDw==
secondaryServerSshPortNo=22
secondaryOsPlatform=windows
secondaryServerIsTrue=true
secondaryServerDir=E: &  



workflowInputDataQuery=select * from workflow_input_details wid where wid.batch_id = ?



logger.homefolder=logs
# Log levels
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Log file configurations
logging.file.name=logs/servicewrapper.log
logging.file.max-size=10MB
logging.file.max-history=60

# Console log pattern
logging.pattern.console = %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n