#should not place spring.** properties here (won't be applied even if placed)
server.servlet.contextPath=/uam
# Port used when deploying the application as a WAR file on an external Tomcat server
server.port=8443
# Uncomment the below line to use this port when running the application as a JAR
# server.port=2588
# Log levels
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Log file configurations
logging.file.name=${commonPathForAllServices}/logs/uam.log
logging.file.max-size=10MB
logging.file.max-history=60

# Console log pattern
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# File log pattern
logging.pattern.file=%d %p %c{1} [%t] %m%n
menuNamesToBeReplaced=Base Upload,Trigger Data Converter,Trigger IC Cleaning,Trigger HOF,Profile Management,Relational Profile Management,Customer Search,Identity Search,Relational Search,Add to Target,Advanced Customer Search,Advanced Relational Search,Bulk Query,Bulk Add Target,Clip Profile Management,Clip Relational Profile Management,Automerge Profile,Automerge GR Sampling,Clip Statistics
app.userExpiry = 3600000
app.token_expiry=3600000
authenticationType=Native
loginInitialInactivityTime=30
loginSubsequentInactivityTime=30
userPasswordSubsequentResetTime=30
userPassword.matchPercentage=0.5
ldap.url=ldap://192.168.1.254:389
ldap.dn=@dc1.posidex.com
modelservice.number=0
inactivity.checkdormacy=43200000
minimum.memory=64
maximum.memory=1024

buildNumber=1
buildDate=2025-06-04